### ISSUE TITLE
how to add lines of output for failed builds to comment with 1.24.1

### ISSUE THREAD

**Issue by hppritcha** [janinko/ghprb#292]
We upgraded our ghprb to the 1.24.1 a few days ago.  In older versions of the plugin there was an option to add lines of output from a failed build to the comment posted to the PR.  I'm unable to find that option with the latest plugin installed.    

How does one set this option with thee 1.24.1 version of the plugin?

**Comment by DavidTanner** [comment]
Under Global configuration -> GitHub Pull Request Builder -> Application Setup -> Append Portion of Build Log, then you can set how many lines you want.

**Comment by hppritcha** [comment]
thanks, but I don't see this option under the application setup for 1.24.1

**Comment by Sanchiz** [comment]
@DavidTanner for some reason this option is not always available. Version 1.29.6 
Here's an example:
![image](https://cloud.githubusercontent.com/assets/1316234/11892511/83ca5540-a571-11e5-9bfc-1803cb9bea45.png)

**Comment by Sanchiz** [comment]
@DavidTanner the most interesting part here that after `sudo service jenkins restart` option `Append portion of build log` appears. This is related to global configuration. Since I have configured one PR builder and there I have overridden configuration, I should enable this option there, but this option is not available there.

Then I've change `config.yml` manually and added there following lines:
```
<org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildLog>
<logExcerptLines>25</logExcerptLines>
</org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildLog>
```
and then I was able to see this option for Jenkins job.

As I understand when we don't have appropriate configuration in config files, we are not able to see configuration form for those items in Jenkins UI. This is pretty confusion.
