### ISSUE TITLE
Is there a way to limit builds per branch ?

### ISSUE THREAD

**Issue by laveesht** [janinko/ghprb#378]
Current Behaviour -
When new commits are pushed to the branch which already has a PR raised , it starts a new build every time.

Desired Behaviour -
When new commits are pushed to the branch which already has a PR raised, it shud stop all running builds for that branch and then start to build with the new commits. 
So only 1 running build per branch at any time.

**Comment by grayaii** [comment]
I just got bit by this today.  As a workaround, you could have a "monitor" job that runs continuously (or a on a cron) that checks running builds of the job and sends an abort signal to the oldest job of the same PR.

**Comment by DavidTanner** [comment]
There is now an option to cancel builds when starting a new one.  Check the latest build.

**Comment by grayaii** [comment]
Sweet! "Cancel build on update" is exactly it.  Thanks man!

**Comment by madhavc** [comment]
@DavidTanner How do we make this property enabled? It still queuing up in the build jobs for every new commit. Is it default?

**Comment by grayaii** [comment]
It's right under "trigger":
<img width="1220" alt="jenkins_screenshot" src="https://cloud.githubusercontent.com/assets/847072/17167136/b845d9c0-53db-11e6-9269-d91de0e03913.png">

**Comment by madhavc** [comment]
Thank you very helpful!


On July 27, 2016 at 12:23:13 AM, grayaii (notifications@github.com) wrote:

It's right under "trigger":
[image: jenkins_screenshot]
<https://cloud.githubusercontent.com/assets/847072/17167136/b845d9c0-53db-11e6-9269-d91de0e03913.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/janinko/ghprb/issues/378#issuecomment-235506893>, or mute
the thread
